ChartValues:
  image:
    tag: scheduler-1.6.0
    repository: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/apache/yunikorn
    pullPolicy: Always
  web:
    image:
      tag: web-1.6.0
      repository: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/apache/yunikorn
      pullPolicy: Always
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 200m
  service:
    selector:
      component: yunikorn-scheduler
    type: LoadBalancer
    ports:
    - port: 9889
      targetPort: 9889
  admissionController:
    image:
      tag: admission-1.6.0
      repository: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1853370294850618/apache/yunikorn
      pullPolicy: Always
    replicaCount: 1
    hostNetwork: true
    priorityClassName: ''
    resources:
      requests:
        memory: 500Mi
        cpu: 100m
      limits:
        memory: 500Mi
        cpu: 500m
    serviceAccount: yunikorn-admission-controller
HelmChartPath: helm
RuntimeType: Kubernetes
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} yunikorn-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "http://$SERVICE_IP:9889/"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/yunikorn
RegionId: cn-hangzhou
OutputType: OutputCommand
Owner: linziqiaolzq
Branch: main
Platform: github
